### ISSUE TITLE
Strict Standards:

### ISSUE THREAD

**Issue by jkirker** [bhays/gravity-forms-wysija#2]
Have you seen this one?

Any chance for a fix?

Strict Standards: Non-static method GFWysija::get_base_path() should not be called statically in /home/user/domains/domain.com/public_html/wp-content/plugins/gravity-forms-wysija-add-on/gravity-forms-wysija.php on line 89

**Comment by bhays** [comment]
I have noticed that in the logs recently. I'll get a fix in place next week. Thanks!

**Comment by jkirker** [comment]
Thanks... It's also breaking the media library causing an eternal 
spinning beachball.  If you aren't seeing the same thing, let me know 
and I'll get you admin access to one of the sites.

**Comment by bhays** [comment]
Just checked in a fix for the static warnings.

I don't think this plugin would affect the media library as there is no external JS being loaded and the plugin itself only interacts with Gravity Forms and Mailpoet.

**Comment by jkirker** [comment]
Thanks Ben..  After your fix there are no more issues with the gallery.  
Don't ask me why. ;)
